add my submission
geeksblabla/blanat pull request #222
Opened 2024-02-27 22:28 UTC by AbidarYassine

2024-02-27 22:44 UTC, aboullaite requested changes

2024-02-27 22:44 UTC, aboullaite commented on submissions/AbidarYassine/Main.java
> +package org.example.test.test2;
Please remove the package

2024-02-28 09:53 UTC, AbidarYassine commented on submissions/AbidarYassine/Main.java
> +package org.example.test.test2;
Done

2024-02-28 16:23 UTC, aboullaite approved these changes

2024-02-28 16:23 UTC, merged