Brute force submission
geeksblabla/blanat pull request #4
Opened 2024-02-16 20:24 UTC by aboullaite

2024-02-17 16:57 UTC, chermehdi requested changes

2024-02-17 16:57 UTC, chermehdi commented on submissions/aboullaite/Main.java
> +package org.example;
package name.

2024-02-17 17:41 UTC, chermehdi commented
@aboullaite this solution seems to be printing the same product twice, can you double check on the sample input?

2024-02-17 18:03 UTC, aboullaite commented
@chermehdi are you running the latest version ? I fixed that this morning indeed

2024-02-18 13:03 UTC, chermehdi approved these changes

2024-02-18 13:03 UTC, merged