Challenge: Anir-Ln submission
geeksblabla/blanat pull request #6
Opened 2024-02-17 13:06 UTC by Anir-Ln

2024-02-18 21:12 UTC, chermehdi requested changes

2024-02-18 21:12 UTC, chermehdi commented on submissions/Anir-Ln/solution.cpp
> +	getline(cin, line);
There is no line for you to skip (README is updated to reflect this).

2024-02-20 08:31 UTC, aboullaite approved these changes

2024-02-20 08:33 UTC, merged

2024-02-20 11:18 UTC, aboullaite commented
Hello @Anir-Ln 
Your submission isn't compiling
```
error: ‘setprecision’ was not declar>
Feb 20 09:00:27 [564907]:    58 |   cout << fixed << setprecision(2);
```