Update README.md
geeksblabla/blanat pull request #65
Opened 2024-02-22 03:21 UTC by mathematikoi

typo fix

2024-02-22 08:56 UTC, aboullaite requested changes

2024-02-22 08:56 UTC, aboullaite commented on README.md
> -> Note that to generate the 1B row file, it will require a couple of minutes to generate and would take around `~22Gb` of disk space.
May I ask why this change ? 1B row of txt data is 22GB indeed ?

2024-02-22 09:14 UTC, chermehdi commented
1B rows using this generator will spit around 22Gb of data (this is coming from the actual file generated on the server, this PR is introducing a typo as opposed to fixing it.  🤣)

2024-02-22 09:14 UTC, closed without merging

2024-02-26 04:02 UTC, mathematikoi commented
> 1B rows using this generator will spit around 22Gb of data (this is coming from the actual file generated on the server, this PR is introducing a typo as opposed to fixing it. 🤣)

whaaaat, my baaad and so sorry